// Code generated by UpdateJson.fsx. Do not hand-edit!

using DanTup.DartAnalysis.Json;

namespace DanTup.DartAnalysis
{
	class ServerGetVersion : Request<Response<ServerGetVersionResponse>>
	{

	}

	class ServerShutdown : Request<Response>
	{

	}

	class ServerSetSubscriptions : Request<ServerSetSubscriptionsRequest, Response>
	{
		public ServerSetSubscriptions(ServerSetSubscriptionsRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisGetErrors : Request<AnalysisGetErrorsRequest, Response<AnalysisGetErrorsResponse>>
	{
		public AnalysisGetErrors(AnalysisGetErrorsRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisGetHover : Request<AnalysisGetHoverRequest, Response<AnalysisGetHoverResponse>>
	{
		public AnalysisGetHover(AnalysisGetHoverRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisReanalyze : Request<Response>
	{

	}

	class AnalysisSetAnalysisRoots : Request<AnalysisSetAnalysisRootsRequest, Response>
	{
		public AnalysisSetAnalysisRoots(AnalysisSetAnalysisRootsRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisSetPriorityFiles : Request<AnalysisSetPriorityFilesRequest, Response>
	{
		public AnalysisSetPriorityFiles(AnalysisSetPriorityFilesRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisSetSubscriptions : Request<AnalysisSetSubscriptionsRequest, Response>
	{
		public AnalysisSetSubscriptions(AnalysisSetSubscriptionsRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisUpdateContent : Request<AnalysisUpdateContentRequest, Response>
	{
		public AnalysisUpdateContent(AnalysisUpdateContentRequest @params)
			: base(@params)
		{
		}
	}

	class AnalysisUpdateOptions : Request<AnalysisUpdateOptionsRequest, Response>
	{
		public AnalysisUpdateOptions(AnalysisUpdateOptionsRequest @params)
			: base(@params)
		{
		}
	}

	class CompletionGetSuggestions : Request<CompletionGetSuggestionsRequest, Response<CompletionGetSuggestionsResponse>>
	{
		public CompletionGetSuggestions(CompletionGetSuggestionsRequest @params)
			: base(@params)
		{
		}
	}

	class SearchFindElementReferences : Request<SearchFindElementReferencesRequest, Response<SearchFindElementReferencesResponse>>
	{
		public SearchFindElementReferences(SearchFindElementReferencesRequest @params)
			: base(@params)
		{
		}
	}

	class SearchFindMemberDeclarations : Request<SearchFindMemberDeclarationsRequest, Response<SearchFindMemberDeclarationsResponse>>
	{
		public SearchFindMemberDeclarations(SearchFindMemberDeclarationsRequest @params)
			: base(@params)
		{
		}
	}

	class SearchFindMemberReferences : Request<SearchFindMemberReferencesRequest, Response<SearchFindMemberReferencesResponse>>
	{
		public SearchFindMemberReferences(SearchFindMemberReferencesRequest @params)
			: base(@params)
		{
		}
	}

	class SearchFindTopLevelDeclarations : Request<SearchFindTopLevelDeclarationsRequest, Response<SearchFindTopLevelDeclarationsResponse>>
	{
		public SearchFindTopLevelDeclarations(SearchFindTopLevelDeclarationsRequest @params)
			: base(@params)
		{
		}
	}

	class SearchGetTypeHierarchy : Request<SearchGetTypeHierarchyRequest, Response<SearchGetTypeHierarchyResponse>>
	{
		public SearchGetTypeHierarchy(SearchGetTypeHierarchyRequest @params)
			: base(@params)
		{
		}
	}

	class EditGetAssists : Request<EditGetAssistsRequest, Response<EditGetAssistsResponse>>
	{
		public EditGetAssists(EditGetAssistsRequest @params)
			: base(@params)
		{
		}
	}

	class EditGetAvailableRefactorings : Request<EditGetAvailableRefactoringsRequest, Response<EditGetAvailableRefactoringsResponse>>
	{
		public EditGetAvailableRefactorings(EditGetAvailableRefactoringsRequest @params)
			: base(@params)
		{
		}
	}

	class EditGetFixes : Request<EditGetFixesRequest, Response<EditGetFixesResponse>>
	{
		public EditGetFixes(EditGetFixesRequest @params)
			: base(@params)
		{
		}
	}

	class EditGetRefactoring : Request<EditGetRefactoringRequest, Response<EditGetRefactoringResponse>>
	{
		public EditGetRefactoring(EditGetRefactoringRequest @params)
			: base(@params)
		{
		}
	}

	class DebugCreateContext : Request<DebugCreateContextRequest, Response<DebugCreateContextResponse>>
	{
		public DebugCreateContext(DebugCreateContextRequest @params)
			: base(@params)
		{
		}
	}

	class DebugDeleteContext : Request<DebugDeleteContextRequest, Response>
	{
		public DebugDeleteContext(DebugDeleteContextRequest @params)
			: base(@params)
		{
		}
	}

	class DebugMapUri : Request<DebugMapUriRequest, Response<DebugMapUriResponse>>
	{
		public DebugMapUri(DebugMapUriRequest @params)
			: base(@params)
		{
		}
	}

	class DebugSetSubscriptions : Request<DebugSetSubscriptionsRequest, Response>
	{
		public DebugSetSubscriptions(DebugSetSubscriptionsRequest @params)
			: base(@params)
		{
		}
	}


}